config/routes.rb
Rails.application.routes.draw do
  resources :shortenings
  get "/:key" => "redirects#show", as: :short
  root "shortenings#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shortening.rb
class Shortening < ApplicationRecord

  validates :key, presence: true, uniqueness: true
  validates :url, presence: true, url: true

  scope :in_recency_order, -> { order(created_at: :desc) }

  def to_param
    key
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController

  def show
    @shortening = Shortening.find_by!(key: params[:key])
    @shortening.increment!(:visit_count)
    redirect_to @shortening.url, status: :moved_permanently, allow_other_host: true
  end

end

app/controllers/shortenings_controller.rb
class ShorteningsController < ApplicationController
  before_action :set_shortening, only: %i[ show edit update destroy ]

  def index
    @shortenings = Shortening.all.in_recency_order.limit(10)
  end

  def show
  end

  def new
    @shortening = Shortening.new
  end

  def edit
  end

  def create
    url = params.require(:shortening).require(:url)

    if (@shortening = ::UrlShortenerService.create_short_mapping!(url))
      redirect_to shortening_url(@shortening.key), notice: "Short url was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @shortening.update(shortening_params)
      redirect_to shortening_url(@shortening.key), notice: "Short url was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shortening.destroy

    redirect_to shortenings_url, notice: "Short url was successfully destroyed."
  end

  private

  def set_shortening
    @shortening = Shortening.find_by!(key: params[:id])
  end

  def shortening_params
    params.require(:shortening).permit(:url, :key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_notice.html.erb
<% if notice.present? %>
  <p class="bg-success p-3 text-white rounded text-center"><%= notice %></p>
<% end %>

app/views/shortenings/_form.html.erb
<%= form_with(model: shortening) do |form| %>
  <% if shortening.errors.any? %>
    <div class="text-danger">
      <h2><%= pluralize(shortening.errors.count, "error") %> prohibited this URL from being saved:</h2>

      <ul>
        <% shortening.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url, class: "form-label" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group mt-4 d-flex gap-2">
    <%= form.submit "Create", class: 'btn btn-primary flex-grow-1' %>
  </div>
<% end %>

app/views/shortenings/_shortening.html.erb
<div id="<%= dom_id shortening %>" class="card">
  <div class="card-body text-center">

    <div class="mb-4 p-3 rounded bg-subtle">
      <div data-controller="clipboard" data-clipboard-success-content="Copied!" class="input-group d-flex">
        <input type="text" value="<%= short_url(shortening) %>" readonly data-clipboard-target="source" class="form-control"/>
        <button type="button" data-action="clipboard#copy" data-clipboard-target="button" class="btn btn-primary">Copy
          to clipboard
        </button>
      </div>
    </div>

    <div class="row gap-2">
      <div class="col-md-6">
        <p class="card-text">
          <strong>Url:</strong>
          <%= shortening.url %>
        </p>
      </div>

      <div class="col-md-2">
        <p class="card-text">
          <strong>Visits:</strong>
          <%= shortening.visit_count %>
        </p>
      </div>

      <div class="col">
        <p class="card-text">
          <strong>Created:</strong>
          <%= l(shortening.created_at) %>
        </p>
      </div>
    </div>
  </div>

</div>

app/views/shortenings/edit.html.erb
<h1>Editing short url</h1>

<%= render "form", shortening: @shortening %>

<div class="d-flex gap-2 mt-2">
  <%= link_to "Back", shortenings_path, class: "btn btn-secondary flex-grow-1" %>
</div>

app/views/shortenings/index.html.erb
<%= render "shared/flash_notice" %>

<div class="text-center mt-4">

  <h1>Welcome to Shortener</h1>

  <p class="mb-4">
    To get started, click the "new short URL" button below.
    <br>
    Then paste the URL you want shortened into the box provided and submit.
    <br>
    You will be given a clean, short URL that you can share with anyone.
  </p>
  <%= link_to "New short url", new_shortening_path, class: 'btn btn-primary' %>
</div>


<hr>
<div class="mt-5">

  <h5>Recent short URLs</h5>
  <div class="d-flex flex-column gap-2">
    <% if @shortenings.load.any? %>

      <% @shortenings.each do |shortening| %>
        <%= render shortening %>
      <% end %>
    <% else %>
      <p class="bg-subtle rounded p-4">No short URLs yet.</p>
    <% end %>
  </div>
</div>

app/views/shortenings/new.html.erb
<h1>Create a new short URL</h1>

<%= render "form", shortening: @shortening %>

<br>

<div class="d-flex gap-2">
  <%= link_to "Back", shortenings_path, class: "btn btn-secondary flex-grow-1" %>
</div>

app/views/shortenings/show.html.erb
<h1 class="text-center">Thank you for using Shortener!</h1>

<p class="text-center">
  Copy the below link and share it with your friends and colleagues.
</p>

<%= render 'shared/flash_notice' %>

<%= render @shortening %>

<div class="d-flex gap-2 mt-4 ">
  <%= link_to "Back", shortenings_path, class: "btn btn-secondary flex-grow-1" %>
</div>